### ISSUE TITLE
Disable plugin in sonar-project.properties

### ISSUE THREAD

**Issue by zakabluk** [sbaudoin/sonar-shellcheck#10]
I'm going to use shell plugin only for any projects, how I can disable plugin work without remove from SQ server?

**Comment by dzmitry-rudnouski** [comment]
Create new shellcheck quality profile, switch off all rules in it and assign to projects that doesn't require shell check.
All other projects will use default shellcheck quality profile.

**Comment by sbaudoin** [comment]
@dzmitry-rudnouski thanks for the answer.

With the new feature #4 of 2.1.0 you can also disable shellcheck on a project basis (which is interesting only if most of your projects require shellcheck)

**Comment by zakabluk** [comment]
> Create new shellcheck quality profile, switch off all rules in it and assign to projects that doesn't require shell check.
> All other projects will use default shellcheck quality profile.

For me this way doesn't work. Was helped only
`sonar.shellcheck.skip=true`
