### ISSUE TITLE
Ability to Skip/Disable Shellcheck Plugin

### ISSUE THREAD

**Issue by znerd** [sbaudoin/sonar-shellcheck#4]
It would be great if I could just disable the ShellCheck plugin by setting a single property, e.g.:
```
sonar.shellcheck.skip=true
```

This would be similar to what e.g. the SonarQube Build Breaker plugin features. It can be disabled by setting a similar property:
```
sonar.buildbreaker.skip=true
```

See:
- https://github.com/SonarQubeCommunity/sonar-build-breaker#user-content-configuration-parameters

**Comment by sbaudoin** [comment]
Hello,

Why not but why not just simply remove all rules from the quality profile?

**Comment by znerd** [comment]
There can be many reasons, including: for debugging, as a temporary measure, etc.

But most importantly (at least to us) to allow control over the behavior from the code. Everything is managed more and more from the code repository.

**Comment by sbaudoin** [comment]
OK, agreed. I'll implement this for the next release.

**Comment by sbaudoin** [comment]
Can you test the following version, please ? https://oss.sonatype.org/content/groups/public/com/github/sbaudoin/sonar-shellcheck-plugin/2.1.0-SNAPSHOT/sonar-shellcheck-plugin-2.1.0-20190417.213544-4.jar
If it is OK for you I'll officially release version 2.1.0.
